http:
  routers:
    proxmox:
      rule: Host(`proxmox.${DOMAIN}`)
      service: proxmox
      entryPoints:
        - https
      tls:
        certResolver: cloudflare
    homeassistant:
      rule: Host(`homeassistant.${DOMAIN}`)
      service: homeassistant
      entryPoints:
        - https
      tls:
        certResolver: cloudflare
    n8n:
      rule: Host(`n8n.${DOMAIN}`)
      service: n8n
      entryPoints:
        - https
      tls:
        certResolver: cloudflare
    pihole:
      rule: Host(`pihole.${DOMAIN}`)
      service: pihole
      entryPoints:
        - https
      tls:
        certResolver: cloudflare

  services:
    proxmox:
      loadBalancer:
        servers:
          - url: https://192.168.0.102:8006 # Use https:// if required
    homeassistant:
      loadBalancer:
        servers:
          - url: http://192.168.0.105:8123
    n8n:
      loadBalancer:
        servers:
          - url: http://192.168.0.109:5678
    pihole:
      loadBalancer:
        servers:
          - url: http://192.168.0.111:80
