services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 8080:8080  # Dashboard (optional, internal only)
    env_file: .env # use .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For Docker provider
      - ./config/traefik.yml:/traefik.yml:ro
      - ./config/services.yml:/services.yml:ro
      - ./config/acme.json:/acme.json
      - ./logs:/logs
    environment:
      CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN} #dns
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=auth
      - traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}  # Hashed format

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - proxy
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}

networks:
  proxy:
    external: true